# Default values for rust-server-helm
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: rustdesk/rustdesk-server
  pullPolicy: IfNotPresent
  tag: "1.1.6"

url: rust.domain.local

rust-public-service:
  replicaCount: 1
  ressources:
    limits:
      cpu: 1
      memory: 1024Mi
  service:
    type: LoadBalancer
  storage: 1Gi

rust-internal-service:
  replicaCount: 1
  ressources:
    limits:
      cpu: 1
      memory: 1024Mi
  storage: 1Gi


config:
  

extraEnvVars: {}

