apiVersion: v1
kind: Service
metadata:
  name: hbbr
spec:
  ports:
    - name: "21117"
      port: 21117
      targetPort: 21117
    - name: "21119"
      port: 21119
      targetPort: 21119
  selector:
    name: hbbr
status:
  loadBalancer: {}
