apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.data.storage }}
  storageClassName: {{ .Values.data.storageClassName }}
