apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-internal-service-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rust-internal-service.storage }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-public-service-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rust-public-service.storage }}
