apiVersion: v1
kind: Service
metadata:
  name: rust-hbbs-service-udp
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "21116"
      port: 21116
      protocol: UDP
      targetPort: 21116
  selector:
    app.kubernetes.io/name: rust-hbbs-service
